### ISSUE TITLE
Inclusion of pdf

### ISSUE THREAD

**Issue by aubertc** [the-au-forml-lab/au_ccs_dissertation_template#12]
Need to implement a simple way of loading a pdf document into the thesis. Ideally, it would preserve the TOC of the inserted document (at the right level), the hyperlinks, etc.

**Comment by nkrusch** [comment]
A starting point:

```latex
\AddToHookNext{shipout/foreground}{\put (0, 0){\pdfbookmark[0]{Cover}{sec:cover}}}
\label{sec:cover}\maketitle\clearpage

\AddToHookNext{shipout/foreground}{\put (0, 0){\pdfbookmark[0]{Acknowledgements}{sec:acks}}}
\input{acknowledgements}\clearpage

\AddToHookNext{shipout/foreground}{\put (0, 0){\pdfbookmark[0]{Abstract}{sec:abstract}}}
\input{abstract}\clearpage

\pdfbookmark[0]{\contentsname}{toc}\tableofcontents\clearpage
\pdfbookmark[0]{\listtablename}{lot}\listoftables\clearpage
\pdfbookmark[0]{\listfigurename}{lof}\listoffigures\clearpage
```

* The `\AddToHookNext{shipout/foreground}{\put (0, 0)` bit is to achor to top of page
* The `\pdfbookmark[0]{display text}{ref}` adds it to the PDF table of contents (only)

**Comment by nkrusch** [comment]
I misread the issue, actually. "loading a pdf document into the thesis..." I am using `includepdf`. I am aware it may break some hyperlinks, but so far it works sufficiently ++ lets me add tables, figures, index terms to the TOC, which is important.

My comment above is to resolve the following issue:

On the printable paper TOC page the headers should be as in the template. 
But in a PDF TOC, in place of *, I wanted hyperlinks for "Table of contents", Tables, Figures, etc. 

<table><tr><td>HAVE</br>
<img width="218" alt="Screen Shot 2024-12-17 at 11 57 24 PM" src="https://github.com/user-attachments/assets/7a8c2165-7f02-4968-95bb-286002e149d8" />
</td><td>WANT</br>
<img width="229" alt="Screen Shot 2024-12-18 at 12 01 58 AM" src="https://github.com/user-attachments/assets/ce7dbb50-4168-42f9-b7a1-cbd58190b1a8" />
</td></tr></table>

This part as in template

<img width="701" alt="Screen Shot 2024-12-18 at 12 03 10 AM" src="https://github.com/user-attachments/assets/ff159693-c633-4b82-b4e2-35a63f3e0ece" />

**Comment by aubertc** [comment]
This is now implemented, and documented around https://github.com/the-au-forml-lab/au_ccs_dissertation_template/blob/main/md_version/main.md#inserting-pdfs

**Comment by nkrusch** [comment]
I don't see in the documentation how to do something like this through the modified interface:
https://github.com/nkrusch/dissertation/blob/1110f8a98beeea4151a20eda458630b0f2123e8d/content.tex#L28-L57

Maybe I misunderstood something? the doc example is very brief.

**Comment by aubertc** [comment]
_The code is its own documentation ©_ ;-)

https://github.com/the-au-forml-lab/au_ccs_dissertation_template/blob/e78567e179bd6218ac587465cbdb26752616c7e5/md_version/templates/head_c.tex#L308-L328

The first parameter is passed as is to `\includepdf[`, and note that labels are created for each page.

There is already an `addtotoc=`, though, so your set-up will probably conflict. You are re-introducing the sections one-by-one if I understand correctly, that's very nice, but I'll never add this level of detail to a template (maybe for an example, though), so I don't think the template should address that -- I may be wrong though, maybe there is a systematic way of doing that, but I really don't think so.

**Comment by nkrusch** [comment]
> The code is its own documentation

No one will want to dig that far; don't rely on it as a way to explain things. 

But thanks for the answer, I am satisfied with it and will close.

**Comment by nkrusch** [comment]
Hold on, I see in the template this boxed style,

<img width="901" alt="Screen Shot 2024-12-26 at 3 23 41 PM" src="https://github.com/user-attachments/assets/b1d1e937-41aa-4559-b01d-f59b221c77a4" />

Is this how they want PDF included? what horror

**Comment by aubertc** [comment]
I don't think they mandate anything, it's a style I've made for my tenure package and am reusing as an example. Use whatever you think is appropriate.

**Comment by nkrusch** [comment]
OK; maybe it is needed to ensure the margins? I think this is a good question to ask the librarian.

**Comment by aubertc** [comment]
Not sure; you are right.
