### ISSUE TITLE
"Alternative format" template

### ISSUE THREAD

**Issue by aubertc** [the-au-forml-lab/au_ccs_dissertation_template#6]
Make a template that can be used using the "alternative format" template. Step 1: document what it must look like.

**Comment by nkrusch** [comment]
Use of Template
Follow the general formatting requirements listed on pages 6-8. Specific formatting
requirements varying from the general requirements are discussed here. 

Figures and Tables Formatting
If using figures and tables from multiple previously published or accepted first-authored works,
numbering will coincide with the manuscript number. For example, figure 4 in published
manuscript 1 will be 1.4 in the thesis/dissertation, and figure 8 in published manuscript 2 will be
2.8 in the thesis/dissertation. See listed examples below.

Organization of Pages

All sections begin on a new page.

1. Title Page
2. Acknowledgements – include a detailed summary of the work performed by other
authors on published or accepted manuscripts used in the thesis/dissertation, if
applicable.
3. Abstract
4. Table of Contents – Published manuscripts precede unpublished research.
5. List of Tables
6. List of Figures
7. I. INTRODUCTION
a. Statement of the problem and specific aims of the overall project.
12
b. Literature review and discussion of the rationale of the project. It is expected
that the literature review will be more comprehensive than those presented in
the included publications.
8. II. PUBLISHED MANUSCRIPTS
a. First published manuscript
b. Second published manuscript
c. Third published manuscript
9. III. UNPUBLISHED RESEARCH – This can include manuscripts, in the journal format, that
have been submitted for publication that are under review at the time of dissertation
submission. Manuscripts that have been rejected or that have not been submitted (in
preparation) cannot be included in the journal format (i.e. must conform to the
traditional dissertation format).
10. IV. DISCUSSION – A comprehensive discussion that integrates the findings of all research
presented in the dissertation and that identifies how the goals or specific aims of the
project were attained, and how the research has answered the hypotheses put forth in
the dissertation.
11. V. SUMMARY – a series of concise remarks summarizing experimental findings and
conclusions.
12. VI. REFERENCES - All literature cited in the dissertation will be included here. Style
should conform to selected style manual. References included in manuscripts must be
renumbered and reformatted (if needed) and included in this section. Literature Cited
sections within the manuscripts should be omitted.
13. VII. APPENDICES – not required, but to include protocol of experiments, figures not
included in text, forms, etc.

Full guide: https://augustauniversity.app.box.com/s/vj0ygpy8tvyqmsbae8y0qp9767ta7jb9

**Comment by nkrusch** [comment]
> Choose Degree from drop-down menu

🙃

**Comment by aubertc** [comment]
Ok, this documentation has been read and implemented -- the only difference with the "standard template" is in the content, which will be up to the student. 

The current template should support edits toward both formats (standard and alternate).
